
server:
  port: 8025

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 7777
  jpa:
    hibernate.ddl-auto: none
    show-sql: true